name: Update Deployment Board
description: Adds deployment Issues to an Automated Deployment Project Board for visual tracking of what has been deployed to each environment.

inputs:
  github-token:
    description: A token with permissions to create and update issues
    required: true
  environment:
    description: The environment the branch, tag or SHA was deployed to, i.e. [DEV|QA|STAGE|DEMO|UAT|PROD]
    required: true
  project-slug:
    description: The repo the deployment will be created in, i.e. [org|owner]/[repo name]
    required: true
  ref:
    description: The branch, tag or SHA that was deployed
    required: true
  deploy-status:
    description: The status of the deployment [error|failure|success]
    required: true
  deployment-message:
    description: Any message to be delivered along side of the status
    required: false
  entities:
    description: The entities that are affected by the deployment, i.e. ["proj-app", "proj-infrastruction", "proj-db"]
    required: true
  instance:
    description: The target deployment server or app service and availability zone, i.e. "NA26", "NA26-slot1", "NA27-blue"
    required: true
  workflow-run-url:
    description: The url of the workflow run, i.e."https://github.com/[owner]/[repo]/actions/runs/[workflow run id]"
    required: true

outputs:
  github-deployment-id:
    description: The id of the of the Git deployment.

runs:
  using: node20
  main: dist/index.js
