name: Build and Check for Changes
on:
  # This workflow uses the pull_request trigger which prevents write permissions and secrets
  # access to the target repository from public forks.  This should remain as a pull_request
  # trigger because checkout, build, format and checking for changes do not need elevated
  # permissions to the repository.  The reduced permissions for public forks is adequate.
  pull_request:
    # Don't include any specific paths here so we always get a build that produces a status
    # check that our Branch Protection Rules can use.  Having a status check also allows us
    # to require that branches be up to date before they are merged.

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Build
        run: npm run build
      - name: Format
        run: npm run format
      - name: Check for unstaged changes
        if: runner.os != 'windows'
        run: ./check-for-unstaged-changes.sh
